import type { Metadata } from "next";
import localFont from "next/font/local";
import StyledComponentsRegistry from "./lib/registry";
import GlobalStyle from "./global-style";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "./Pretendard-Regular.woff2",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body>
        <StyledComponentsRegistry>
          <Providers>
            <GlobalStyle />
            {children}
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
